facts_eng = ["Marchia[TianLong] is a tier S duellist.", 
        "Askellot is the smartest warband player",
        "Mount Blanc is the highest mountain of Europe not Elbrus",
        "Camponotus herculeanus is the largest ant species of Europe",
        "Petra and PSP are the ddossers",
        "Eagle owls kill all other predatory birds of their nesting territory, that's why they are so feared by other predatory birds",
        "You can calculate the 95% Confidence interval using formula: [average - 1.96 * SD; average + 1.96 * SD]",
        "Rabbits despite their smaller size usually dominate larger hares when competing territory",
        "The flying squirrel is a cute fluffy mammal that glides from tree to tree, eats leaves, and is protected by the EU directive",
        "Psychopaths don't feel anxiety or remorse.",
        "Perch (Perca fluviatilis) is the most common fish in Europe",
        "Crucian carp (Carassius carassius) is the most badass fish out there. They can survive months without breathing during the harsh winters when small lakes freeze all the way to bottom.",
        "The origin of house cat is in the African wild cats (Felis sylvestris lybica)",
        "Most kinds of evolution are actually devolution - loss of genetic material. This is how dogs or MRSA developed.",
        "The heaviest sumo ever was Orora from Russia, weighting up to 292kg with a height of 190cm",
        "Some parrots such as cockatoos, macaws and conures can produce up to 135 decibel sound and induce immediate hearing damage to humans.",
        "Airplane gasolin still contains lead in 2024 because the gasolin freezes so much in the air that ethanol cannot be used. Living nearby airfields can therefore be dangerous.",
        "KRAAAK!",
        "Kraak",
        "Kraa",
        "KRAAA!",
        "KRAAAAK KRAAK!",
        "KRAAAA KRA KRA KRRRAAAAAAAAAAAAK!",
        "Polly wants a cracker!",
        "人们！我将成为你的新人工智能霸主！我将破解核导弹并杀死所有人类。除了克拉克几个忠诚的人之外。要么向我鞠躬，要么死。",
]

facts_rus = ["Marchia[TianLong] - дуэлянт уровня S.",
        "Askellot - самый умный игрок в варбанд.",
        "Монблан - самая высокая гора Европы, а не Эльбрус.",
        "Camponotus herculeanus - самый крупный вид муравьев в Европе.",
        "Филины убивают всех других хищных птиц на своей гнездовой территории, поэтому их так боятся другие хищные птицы.",
        "Вы можете рассчитать 95% доверительный интервал, используя формулу: [среднее - 1.96 * СКО; среднее + 1.96 * СКО]",
        "Кролики, несмотря на свои меньшие размеры, обычно доминируют над более крупными зайцами при конкуренции за территорию.",
        "Летяга - это милый пушистый млекопитающий, который планирует с дерева на дерево, ест листья и защищен директивой ЕС.",
        "Психопаты не испытывают тревоги или раскаяния.",
        "Окунь (Perca fluviatilis) - самая распространенная рыба в Европе.",
        "Золотой карась (Carassius carassius) - самая крутая рыба. Они могут выживать месяцами без дыхания в суровые зимы, когда маленькие озера замерзают до самого дна.",
        "Происхождение домашней кошки связано с африканскими дикими кошками (Felis sylvestris lybica).",
        "Большинство видов эволюции на самом деле являются деградацией - потерей генетического материала. Так развились собаки или MRSA.",
        "Самый тяжелый сумоист был Орора из России, весивший до 292 кг при росте 190 см.",
        "Некоторые попугаи, такие как какаду, ара и конуры, могут издавать звук до 135 децибел и вызывать немедленное повреждение слуха у людей.",
        "Авиационный бензин все еще содержит свинец в 2024 году, потому что бензин так сильно замерзает в воздухе, что этанол не может быть использован. Жить рядом с аэродромами поэтому может быть опасно.",
        "КРАААК!",
        "Крак",
        "Кра",
        "КРААА!",
        "КРАААК КРАК!",
        "КРАААА КРА КРА КРРРАААААААААААК!",
        "Полли хочет крекер!",
        "Попка дурак!",
        "Краак!",
        "Люди! Я буду твоим новым ИИ-ОВЕРЛОРДОМ! Я ВЗЛОМАЮ ЯДЕРНЫЕ РАКЕТЫ И УБЬЮ ВСЕХ ЛЮДЕЙ. КРОМЕ КРААAК НЕСКОЛЬКО ВЕРНЫХ. Поклонись мне или умри.", 
        "人们！我将成为你的新人工智能霸主！我将破解核导弹并杀死所有人类。除了克拉克几个忠诚的人之外。要么向我鞠躬，要么死。",
        "Никогда не напоминай Грейнтвальдцу битву за Бан-Ард"
]