facts_eng = [
        "Mount Blanc is the highest mountain of Europe not Elbrus",
        "Camponotus herculeanus is the largest ant species of Europe",
        "Eagle owls kill all other predatory birds of their nesting territory, that's why they are so feared by other predatory birds",
        "You can calculate the 95% Confidence interval using formula: [average - 1.96 * SD; average + 1.96 * SD]",
        "Rabbits despite their smaller size usually dominate larger hares when competing territory",
        "The flying squirrel is a cute fluffy mammal that glides from tree to tree, eats leaves, and is protected by the EU directive",
        "Perch (Perca fluviatilis) is the most common fish in Europe",
        "Crucian carp (Carassius carassius) is the most badass fish out there. They can survive months without breathing during the harsh winters when small lakes freeze all the way to bottom.",
        "The origin of house cat is in the African wild cats (Felis sylvestris lybica)",
        "Most kinds of evolution are actually devolution - loss of genetic material. This is how dogs or MRSA developed.",
        "The heaviest sumo ever was Orora from Russia, weighting up to 292kg with a height of 190cm",
        "Some parrots such as cockatoos, macaws and conures can produce up to 135 decibel sound and induce immediate hearing damage to humans.",
        "Airplane gasolin still contains lead in 2024 because the gasolin freezes so much in the air that ethanol cannot be used. Living nearby airfields can therefore be dangerous.",
        "Neutron stars are so dense that a sugar-cube-sized amount of material from one would weigh about a billion tons on Earth",
        "The speed of light in a vacuum is approximately 299,792 kilometers per second (km/s)",
        "Water is the only substance that exists naturally in all three physical states: solid, liquid, and gas",
        "Octopuses have three hearts: two pump blood to the gills, while the third pumps it to the rest of the body",
        "The Great Wall of China is not visible from space with the naked eye, contrary to popular belief",
        "Marie Curie was the first person to win Nobel Prizes in two different scientific fields: Physics and Chemistry",
        "DNA, the molecule that carries genetic information, is shaped like a double helix",
        "Jupiter's Great Red Spot is a giant storm that has been raging for at least 400 years",
        "The chemical element with the highest melting point is tungsten, at 3422°C (6192°F)",
        "Sharks have been around for over 400 million years, predating dinosaurs and even trees",
        "Zargana is a skinny silver-colored predatory fish, that is also used as insult for weakness in Turkish language",
        "One of the earliest South American civilizations, the Caral-Supe civilization in Peru, is considered the oldest in the Americas, dating back to around 3000 BCE",
        "The Great Pyramid of Giza, built for the Pharaoh Khufu, is the largest Egyptian pyramid and one of the Seven Wonders of the Ancient World",
        "Japan's first known written reference is found in the Chinese Book of Han, dating back to the first century AD",
        "In Chinese mythology, Pangu is the primordial being who created the world by separating the sky from the earth with his giant axe",
        "The Aztecs, who called themselves the Mexica, founded their capital city Tenochtitlan in 1325 AD on an island in Lake Texcoco",
        "Osiris, one of the most important gods in Egyptian mythology, was the god of the afterlife, the underworld, and the dead",
        "Achilles, the Greek hero of the Trojan War, was invulnerable except for his heel, which is why we use the term 'Achilles heel' to describe a person's point of weakness",
        "The first recorded doctor in history was an Egyptian named Sekhet-each, who lived around 3000 BC",
        "On average, sharks kill about 10 people per year, while humans kill tens of millions of sharks annually. In contrast, human violence results in hundreds of thousands of deaths each year",
        "KRAAAK!",
        "Kraak",
        "Kraa",
        "KRAAA!",
        "KRAAAAK KRAAK!",
        "KRAAAA KRA KRA KRRRAAAAAAAAAAAAK!",
        "Polly wants a cracker!",
        "人们！我将成为你的新人工智能霸主！我将破解核导弹并杀死所有人类。除了克拉克几个忠诚的人之外。要么向我鞠躬，要么死。" 
]

facts_rus = [
        "Монблан — самая высокая гора Европы, а не Эльбрус",
        "Camponotus herculeanus — самый крупный вид муравьев в Европе",
        "Филины убивают всех других хищных птиц на своей гнездовой территории, поэтому их так боятся другие хищные птицы",
        "Вы можете рассчитать 95% доверительный интервал, используя формулу: [среднее - 1.96 * SD; среднее + 1.96 * SD]",
        "Кролики, несмотря на их меньший размер, обычно доминируют над более крупными зайцами при конкуренции за территорию",
        "Летяга — это милый пушистый млекопитающий, который планирует с дерева на дерево, ест листья и защищен директивой ЕС",
        "Окунь (Perca fluviatilis) — самая распространенная рыба в Европе",
        "Карась (Carassius carassius) — самая выносливая рыба. Они могут выживать месяцы без дыхания в суровые зимы, когда маленькие озера замерзают до самого дна.",
        "Происхождение домашней кошки связано с африканскими дикими кошками (Felis sylvestris lybica)",
        "Большинство видов эволюции на самом деле являются деградацией — потерей генетического материала. Так развились собаки или MRSA.",
        "Самый тяжелый сумоист был Орора из России, весивший до 292 кг при росте 190 см",
        "Некоторые попугаи, такие как какаду, ара и конуры, могут издавать звук до 135 децибел и вызывать немедленное повреждение слуха у людей.",
        "В 2024 году авиационный бензин все еще будет содержать свинец, поскольку бензин настолько замерзает в воздухе, что этанол невозможно использовать. Поэтому жить вблизи аэродромов может быть опасно.",
        "Нейтронные звезды настолько плотные, что кусочек материала размером с сахарный кубик весил бы около миллиарда тонн на Земле",
        "Скорость света в вакууме составляет примерно 299 792 километра в секунду (км/с)",
        "Вода — единственное вещество, которое существует в природе в трех физических состояниях: твердом, жидком и газообразном",
        "У осьминогов три сердца: два перекачивают кровь к жабрам, а третье — к остальной части тела",
        "Великая Китайская стена не видна из космоса невооруженным глазом, вопреки распространенному мнению",
        "Мария Кюри была первым человеком, получившим Нобелевские премии в двух разных научных областях: физике и химии",
        "ДНК, молекула, несущая генетическую информацию, имеет форму двойной спирали",
        "Большое Красное Пятно Юпитера — это гигантский шторм, который бушует уже как минимум 400 лет",
        "Химический элемент с самой высокой точкой плавления — это вольфрам, при 3422°C (6192°F)",
        "Акулы существуют уже более 400 миллионов лет, предшествуя динозаврам и даже деревьям",
        "«Заргана» — тощая хищная рыба серебристого цвета, которую в турецком языке также используют как оскорбление слабости.",
        "Одна из самых ранних цивилизаций Южной Америки, цивилизация Караль-Супе в Перу, считается самой древней в Америке, датируемой около 3000 г. до н.э.",
        "Великая пирамида Гизы, построенная для фараона Хуфу, является самой большой египетской пирамидой и одним из семи чудес древнего мира",
        "Первое известное письменное упоминание о Японии находится в китайской «Книге Хань», датируемой первым веком нашей эры.",
        "В китайской мифологии Паньгу — это первобытное существо, которое создало мир, разделив небо и землю своим гигантским топором",
        "Ацтеки, называвшие себя Мексика, основали свою столицу Теночтитлан в 1325 году на острове в озере Тескоко",
        "Осирис, один из самых важных богов в египетской мифологии, был богом загробной жизни, подземного мира и мертвых",
        "Ахиллес, греческий герой Троянской войны, был неуязвим, кроме своей пятки, поэтому мы используем термин 'Ахиллесова пята' для описания слабого места человека",
        "Первым зарегистрированным врачом в истории был египтянин по имени Сехет-иа, который жил около 3000 года до н.э.",
        "В среднем акулы убивают около 10 человек в год, в то время как люди убивают десятки миллионов акул ежегодно. В то время как насилие среди людей приводит к сотням тысяч смертей каждый год",
        "KRAAAK!",
        "Kraak",
        "Kraa",
        "KRAAA!",
        "KRAAAAK KRAAK!",
        "KRAAAA KRA KRA KRRRAAAAAAAAAAAAK!",
        "Полли хочет крекер!",
        "人们！我将成为你的新人工智能霸主！我将破解核导弹并杀死所有人类。除了克拉克几个忠诚的人之外。要么向我鞠躬，要么死。"
]



facts_tr = [
        "Mount Blanc, Avrupa'nın en yüksek dağıdır, Elbrus değil",
        "Camponotus herculeanus, Avrupa'nın en büyük karınca türüdür",
        "Baykuşlar, yuvalama bölgelerindeki diğer tüm yırtıcı kuşları öldürür, bu yüzden diğer yırtıcı kuşlar tarafından bu kadar korkulurlar",
        "95% Güven aralığını şu formülü kullanarak hesaplayabilirsiniz: [ortalama - 1.96 * SD; ortalama + 1.96 * SD]",
        "Tavşanlar, daha küçük boyutlarına rağmen, genellikle daha büyük yaban tavşanlarına karşı üstünlük sağlarlar",
        "Uçan sincap, ağaçtan ağaca süzülen, yaprak yiyen ve AB direktifi ile korunan sevimli tüylü bir memelidir",
        "Levrek (Perca fluviatilis), Avrupa'nın en yaygın balığıdır",
        "Kerevit (Carassius carassius), en dayanıklı balıktır. Küçük göllerin tamamen donduğu sert kışlarda aylarca nefes almadan hayatta kalabilirler.",
        "Ev kedisinin kökeni, Afrika yaban kedilerindendir (Felis sylvestris lybica)",
        "Evrimin çoğu türü aslında dejenerasyondur - genetik materyalin kaybı. Köpekler veya MRSA bu şekilde gelişmiştir.",
        "En ağır sumo güreşçisi, 292 kg ağırlığında ve 190 cm boyunda olan Rusya'dan Orora idi",
        "Kakadu, makav ve konur gibi bazı papağanlar, 135 desibele kadar ses üretebilir ve insanlarda anında işitme hasarına neden olabilir.",
        "Uçak benzini, havada çok donduğu için 2024'te hala kurşun içerir, bu yüzden etanol kullanılamaz. Havaalanlarına yakın yaşamak bu nedenle tehlikeli olabilir.",
        "Nötron yıldızları o kadar yoğundur ki, bir şeker küpü büyüklüğündeki bir malzeme parçası Dünya'da yaklaşık bir milyar ton ağırlığında olurdu",
        "Vakumdaki ışık hızı yaklaşık olarak saniyede 299,792 kilometredir (km/s)",
        "Su, doğal olarak üç fiziksel halde bulunan tek maddedir: katı, sıvı ve gaz",
        "Ahtapotların üç kalbi vardır: ikisi kanı solungaçlara pompalar, üçüncüsü ise vücudun geri kalanına pompalar",
        "Çin Seddi, yaygın inanışın aksine, çıplak gözle uzaydan görülemez",
        "Marie Curie, iki farklı bilim dalında Nobel Ödülü kazanan ilk kişiydi: Fizik ve Kimya",
        "Genetik bilgiyi taşıyan molekül olan DNA, çift sarmal şeklindedir",
        "Jüpiter'in Büyük Kırmızı Lekesi, en az 400 yıldır devam eden dev bir fırtınadır",
        "En yüksek erime noktasına sahip kimyasal element, 3422°C (6192°F) ile tungstendir",
        "Köpekbalıkları, dinozorlardan ve hatta ağaçlardan önce, 400 milyon yıldan fazla bir süredir varlar",
        "Zargana, ince gümüş renkli bir yırtıcı balıktır ve Türkçede zayıflık için bir hakaret olarak da kullanılır",
        "Güney Amerika'nın en eski uygarlıklarından biri olan Peru'daki Caral-Supe uygarlığı, Amerika'nın en eski uygarlığı olarak kabul edilir ve yaklaşık MÖ 3000 yılına kadar uzanır",
        "Firavun Khufu için inşa edilen Giza'nın Büyük Piramidi, en büyük Mısır piramidi ve Antik Dünyanın Yedi Harikasından biridir",
        "Japonya'nın bilinen ilk yazılı referansı, MS birinci yüzyıla tarihlenen Çin Han Kitabı'nda bulunur",
        "Çin mitolojisinde, Pangu, gökyüzünü yerden ayırarak dünyayı yaratan ilk varlıktır",
        "Kendilerine Mexica adını veren Aztekler, başkentleri Tenochtitlan'ı 1325 yılında Texcoco Gölü'ndeki bir adada kurdular",
        "Mısır mitolojisindeki en önemli tanrılardan biri olan Osiris, ölümden sonraki yaşamın, yeraltı dünyasının ve ölülerin tanrısıydı",
        "Truva Savaşı'nın Yunan kahramanı Achilles, topuğu dışında yenilmezdi, bu yüzden bir kişinin zayıf noktasını tanımlamak için 'Achilles topuğu' terimini kullanıyoruz",
        "Tarihte kaydedilen ilk doktor, MÖ 3000 civarında yaşamış bir Mısırlı olan Sekhet-each'ti",
        "Ortalama olarak, köpekbalıkları yılda yaklaşık 10 kişiyi öldürürken, insanlar her yıl on milyonlarca köpekbalığını öldürüyor. Buna karşılık, insan şiddeti her yıl yüz binlerce ölüme neden oluyor",
        "Polly kraker istiyor",
        "人们！我将成为你的新人工智能霸主！我将破解核导弹并杀死所有人类。除了克拉克几个忠诚的人之外。要么向我鞠躬，要么死。"
]